version: "3"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
      - ./db-init/:/docker-entrypoint-initdb.d/
    expose:
      - 5432
    ports:
      - 8079:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: unless-stopped
  everkeep:
    image: everkeep:latest
    network_mode: bridge
    container_name: everkeep
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  pgdata:
  db-init: