version: "3.8"
services:
  database:
    image: postgres:14.4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRES_HOST_PORT:$POSTGRES_DOCKER_PORT
    volumes:
      - ./db_data:/var/lib/postgres
  app:
    image: everkeep-api:latest
    depends_on:
      database:
        condition: service_healthy
    build: .
    restart: on-failure
    env_file: .env
    ports:
      - $APP_HOST_PORT:$APP_DOCKER_PORT
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:$POSTGRES_DOCKER_PORT/$POSTGRES_DB?user=$POSTGRES_USER&password=$POSTGRES_PASSWORD
      - SPRING_MAIL_HOST=$MAIL_HOST
      - SPRING_MAIL_PORT=$MAIL_PORT
      - SPRING_MAIL_PROTOCOL=$MAIL_PROTOCOL
      - SPRING_MAIL_USERNAME=$MAIL_USERNAME
      - SPRING_MAIL_PASSWORD=$MAIL_PASSWORD
      - INTEGRATION_UI_URL=$INTEGRATION_UI_URL
      - JWT_SECRET=$JWT_SECRET
    stdin_open: true
    tty: true
