spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    protocol: ${SPRING_MAIL_PROTOCOL}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
  packages-to-scan:
    - com.everkeep

jwt:
  secret: ${JWT_SECRET}
  expirationTimeSec: 900 # 15 minutes

verificationToken:
  expirationTimeSec: 2592000 # 1 month
