spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    locations:
      - classpath:/db/migration
      - classpath:/db/testdata

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.TYPE: trace
    org.springframework.security: debug

jwt:
  secret: TVFX8dwOWzOQbMecjnnZ3foXeBVDZK0ItpdXxlz6IgGjVJNU4cTo3Evj7nIE0n

integration:
  uiUrl: http://localhost:4200

