server:
  error:
    include-stacktrace: never

spring:
  datasource:
    url: ${DATABASE_URL:}
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  mail:
    host: ${SPRING_MAIL_HOST:}
    port: ${SPRING_MAIL_PORT:}
    protocol: ${SPRING_MAIL_PROTOCOL:}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}

springdoc:
  swagger-ui:
    disable-swagger-default-url: true

jwt:
  secret: ${JWT_SECRET:}
  expiry-duration: ${JWT_EXPIRY_DURATION:PT15M}

verification-token:
  expiry-duration: ${VERIFICATION_TOKEN_EXPIRY_DURATION_SEC:P30D}

integration:
  uiUrl: ${INTEGRATION_UI_URL:}
