name: "Build"

on: push

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        language: [ 'java' ]
        distribution: [ 'liberica' ]
        java_version: [ 17 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java_version }}
          distribution: ${{ matrix.distribution }}
          cache: 'gradle'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
    
      - name: Execute Gradle build
        run: ./gradlew build

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
            generate-branches-badge: true
            jacoco-csv-file: app/build/reports/jacoco/test/jacocoTestReport.csv

      - name: Log coverage percentage
        run: |
            echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
            echo "branch coverage = ${{ steps.jacoco.outputs.branches }}   

      - name: Commit the badge (if it changed)
        run: |
            if [[ `git status --porcelain` ]]; then
              git config --global user.name 'Vladislav Shveikin'
              git config --global user.email '37498620@users.noreply.github.com'
              git add -A
              git commit -m "Autogenerated JaCoCo coverage badge"
              git push
            fi

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
            name: jacoco-report
            path: app/build/reports/jacoco/test/jacocoTestReport.csv
